interface ItemType {
  id: number;
  like: boolean;
  img: string;
  name: string;
  description: string;
  category:
    | "tv"
    | "washing machine"
    | "cooker"
    | "air conditioner"
    | "generator"
    | "blender";
  amount: number | string;
  ratings: number;
  ratings_count: number;
  slug: string;
  section: "latest deals" | "special offers" | "amazing discount";
}

const Item: ItemType[] = [
  {
    id: 0,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "tv",
    amount: "N1,000,000",
    ratings: 35,
    ratings_count: 10,
    slug: "Gas Cooker",
    section: "latest deals",
  },
  {
    id: 1,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "tv",
    amount: "N1,000,000",
    ratings: 30,
    ratings_count: 11,
    slug: "Gas Cooker",
    section: "latest deals",
  },
  {
    id: 2,
    like: false,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "tv",
    amount: "N1,000,000",
    ratings: 15,
    ratings_count: 10,
    slug: "Gas Cooker",
    section: "latest deals",
  },
  {
    id: 3,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "tv",
    amount: "N2,000,000",
    ratings: 45,
    ratings_count: 10,
    slug: "Gas Cooker",
    section: "latest deals",
  },
  {
    id: 4,
    like: false,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "tv",
    amount: "N100,000",
    ratings: 35,
    ratings_count: 10,
    slug: "Gas Cooker",
    section: "latest deals",
  },
  {
    id: 5,
    like: false,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "tv",
    amount: "N1,000,000",
    ratings: 40,
    ratings_count: 12,
    slug: "Gas Cooker",
    section: "latest deals",
  },
  {
    id: 6,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "tv",
    amount: "N9,999",
    ratings: 50,
    ratings_count: 10,
    slug: "Gas Cooker",
    section: "amazing discount",
  },
  {
    id: 7,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "tv",
    amount: "N90,999",
    ratings: 43,
    ratings_count: 9,
    slug: "Gas Cooker",
    section: "amazing discount",
  },
  {
    id: 8,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "tv",
    amount: "N1,500,000",
    ratings: 45,
    ratings_count: 10,
    slug: "Gas Cooker",
    section: "amazing discount",
  },
  {
    id: 9,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "tv",
    amount: "N9,999",
    ratings: 35,
    ratings_count: 7,
    slug: "Gas Cooker",
    section: "amazing discount",
  },
  {
    id: 10,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "tv",
    amount: "N12,999",
    ratings: 20,
    ratings_count: 5,
    slug: "Gas Cooker",
    section: "amazing discount",
  },
  {
    id: 11,
    like: false,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "cooker",
    amount: "N100,500",
    ratings: 30,
    ratings_count: 8,
    slug: "Gas Cooker",
    section: "amazing discount",
  },
  {
    id: 12,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "cooker",
    amount: "N90,999",
    ratings: 40,
    ratings_count: 10,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 13,
    like: false,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "cooker",
    amount: "N180,999",
    ratings: 15,
    ratings_count: 4,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 14,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "cooker",
    amount: "N75,800",
    ratings: 40,
    ratings_count: 9,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 15,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "cooker",
    amount: "N2,500,500",
    ratings: 50,
    ratings_count: 10,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 16,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "cooker",
    amount: "N5,999",
    ratings: 37,
    ratings_count: 9,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 17,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "cooker",
    amount: "N90,999",
    ratings: 60,
    ratings_count: 15,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 18,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "cooker",
    amount: "N1,500,000",
    ratings: 45,
    ratings_count: 10,
    slug: "Gas Cooker",
    section: "amazing discount",
  },
  {
    id: 19,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "washing machine",
    amount: "N9,999",
    ratings: 35,
    ratings_count: 7,
    slug: "Gas Cooker",
    section: "amazing discount",
  },
  {
    id: 20,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "washing machine",
    amount: "N12,999",
    ratings: 20,
    ratings_count: 5,
    slug: "Gas Cooker",
    section: "amazing discount",
  },
  {
    id: 21,
    like: false,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "washing machine",
    amount: "N100,500",
    ratings: 30,
    ratings_count: 8,
    slug: "Gas Cooker",
    section: "amazing discount",
  },
  {
    id: 22,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "washing machine",
    amount: "N90,999",
    ratings: 40,
    ratings_count: 10,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 23,
    like: false,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "washing machine",
    amount: "N180,999",
    ratings: 15,
    ratings_count: 4,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 24,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "washing machine",
    amount: "N75,800",
    ratings: 40,
    ratings_count: 9,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 25,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "washing machine",
    amount: "N2,500,500",
    ratings: 50,
    ratings_count: 10,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 26,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "washing machine",
    amount: "N5,999",
    ratings: 37,
    ratings_count: 9,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 27,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "washing machine",
    amount: "N90,999",
    ratings: 60,
    ratings_count: 15,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 28,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "blender",
    amount: "N1,500,000",
    ratings: 45,
    ratings_count: 10,
    slug: "Gas Cooker",
    section: "amazing discount",
  },
  {
    id: 29,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "blender",
    amount: "N9,999",
    ratings: 35,
    ratings_count: 7,
    slug: "Gas Cooker",
    section: "amazing discount",
  },
  {
    id: 30,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "blender",
    amount: "N12,999",
    ratings: 20,
    ratings_count: 5,
    slug: "Gas Cooker",
    section: "amazing discount",
  },
  {
    id: 31,
    like: false,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "blender",
    amount: "N100,500",
    ratings: 30,
    ratings_count: 8,
    slug: "Gas Cooker",
    section: "amazing discount",
  },
  {
    id: 32,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "blender",
    amount: "N90,999",
    ratings: 40,
    ratings_count: 10,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 33,
    like: false,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "blender",
    amount: "N180,999",
    ratings: 15,
    ratings_count: 4,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 34,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "air conditioner",
    amount: "N75,800",
    ratings: 40,
    ratings_count: 9,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 35,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "air conditioner",
    amount: "N2,500,500",
    ratings: 50,
    ratings_count: 10,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 36,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "air conditioner",
    amount: "N5,999",
    ratings: 37,
    ratings_count: 9,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 37,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "air conditioner",
    amount: "N90,999",
    ratings: 60,
    ratings_count: 15,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 38,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "generator",
    amount: "N1,500,000",
    ratings: 45,
    ratings_count: 10,
    slug: "Gas Cooker",
    section: "amazing discount",
  },
  {
    id: 39,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "generator",
    amount: "N9,999",
    ratings: 35,
    ratings_count: 7,
    slug: "Gas Cooker",
    section: "amazing discount",
  },
  {
    id: 40,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "generator",
    amount: "N12,999",
    ratings: 20,
    ratings_count: 5,
    slug: "Gas Cooker",
    section: "amazing discount",
  },
  {
    id: 41,
    like: false,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "generator",
    amount: "N100,500",
    ratings: 30,
    ratings_count: 8,
    slug: "Gas Cooker",
    section: "amazing discount",
  },
  {
    id: 42,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "generator",
    amount: "N90,999",
    ratings: 40,
    ratings_count: 10,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 43,
    like: false,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "generator",
    amount: "N180,999",
    ratings: 15,
    ratings_count: 4,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 44,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "generator",
    amount: "N75,800",
    ratings: 40,
    ratings_count: 9,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 45,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "generator",
    amount: "N2,500,500",
    ratings: 50,
    ratings_count: 10,
    slug: "Gas Cooker",
    section: "special offers",
  },
];

export { Item };
export type { ItemType };
