interface ItemType {
  id: number;
  like: boolean;
  img: string;
  name: string;
  description: string;
  category:
    | "tv"
    | "washing machine"
    | "cooker"
    | "air conditioner"
    | "generator"
    | "blender"
    | "freezer";
  amount: number;
  ratings: number;
  ratings_count: number;
  slug: string;
  section: "latest deals" | "special offers" | "amazing discount";
}

const Item: ItemType[] = [
  {
    id: 0,
    like: true,
    img: "TV.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "tv",
    amount: 1000000,
    ratings: 35,
    ratings_count: 10,
    slug: "Television",
    section: "amazing discount",
  },
  {
    id: 1,
    like: true,
    img: "TV.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "tv",
    amount: 1000000,
    ratings: 30,
    ratings_count: 11,
    slug: "Television",
    section: "amazing discount",
  },
  {
    id: 2,
    like: false,
    img: "TV.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "tv",
    amount: 1000000,
    ratings: 15,
    ratings_count: 10,
    slug: "Television",
    section: "special offers",
  },
  {
    id: 3,
    like: true,
    img: "TV.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "tv",
    amount: 2000000,
    ratings: 45,
    ratings_count: 10,
    slug: "Television",
    section: "latest deals",
  },
  {
    id: 4,
    like: false,
    img: "TV.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "tv",
    amount: 100000,
    ratings: 35,
    ratings_count: 10,
    slug: "Television",
    section: "special offers",
  },
  {
    id: 5,
    like: false,
    img: "TV.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "tv",
    amount: 1000000,
    ratings: 40,
    ratings_count: 12,
    slug: "Television",
    section: "latest deals",
  },
  {
    id: 6,
    like: true,
    img: "TV.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "tv",
    amount: 9999,
    ratings: 50,
    ratings_count: 10,
    slug: "Television",
    section: "amazing discount",
  },
  {
    id: 7,
    like: true,
    img: "TV.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "tv",
    amount: 90999,
    ratings: 43,
    ratings_count: 9,
    slug: "Television",
    section: "amazing discount",
  },
  {
    id: 8,
    like: true,
    img: "TV.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "tv",
    amount: 1500000,
    ratings: 45,
    ratings_count: 10,
    slug: "Television",
    section: "amazing discount",
  },
  {
    id: 9,
    like: true,
    img: "TV.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "tv",
    amount: 9999,
    ratings: 35,
    ratings_count: 7,
    slug: "Television",
    section: "latest deals",
  },
  {
    id: 10,
    like: true,
    img: "TV.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "tv",
    amount: 12999,
    ratings: 20,
    ratings_count: 5,
    slug: "Gas Cooker",
    section: "amazing discount",
  },
  {
    id: 11,
    like: false,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "cooker",
    amount: 100500,
    ratings: 30,
    ratings_count: 8,
    slug: "Gas Cooker",
    section: "amazing discount",
  },
  {
    id: 12,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "cooker",
    amount: 90999,
    ratings: 40,
    ratings_count: 10,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 13,
    like: false,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "cooker",
    amount: 180999,
    ratings: 15,
    ratings_count: 4,
    slug: "Gas Cooker",
    section: "latest deals",
  },
  {
    id: 14,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "cooker",
    amount: 75800,
    ratings: 40,
    ratings_count: 9,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 15,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "cooker",
    amount: 2500500,
    ratings: 50,
    ratings_count: 10,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 16,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "cooker",
    amount: 5999,
    ratings: 37,
    ratings_count: 9,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 17,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "cooker",
    amount: 90999,
    ratings: 60,
    ratings_count: 15,
    slug: "Gas Cooker",
    section: "special offers",
  },
  {
    id: 18,
    like: true,
    img: "GasCooker.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "cooker",
    amount: 1500000,
    ratings: 45,
    ratings_count: 10,
    slug: "Gas Cooker",
    section: "amazing discount",
  },
  {
    id: 19,
    like: true,
    img: "WashingMachine1.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "washing machine",
    amount: 9999,
    ratings: 35,
    ratings_count: 7,
    slug: "Washing MAchine",
    section: "amazing discount",
  },
  {
    id: 20,
    like: true,
    img: "WashingMachines.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "washing machine",
    amount: 12999,
    ratings: 20,
    ratings_count: 5,
    slug: "Washing Machine",
    section: "latest deals",
  },
  {
    id: 21,
    like: false,
    img: "WashingMachine1.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "washing machine",
    amount: 100500,
    ratings: 30,
    ratings_count: 8,
    slug: "Washing Machine",
    section: "amazing discount",
  },
  {
    id: 22,
    like: true,
    img: "WashingMachine2.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "washing machine",
    amount: 90999,
    ratings: 40,
    ratings_count: 10,
    slug: "Washing Machine",
    section: "special offers",
  },
  {
    id: 23,
    like: false,
    img: "WashingMachines.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "washing machine",
    amount: 180999,
    ratings: 15,
    ratings_count: 4,
    slug: "Washing Machine",
    section: "amazing discount",
  },
  {
    id: 24,
    like: true,
    img: "WashingMachine2.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "washing machine",
    amount: 75800,
    ratings: 40,
    ratings_count: 9,
    slug: "Washing Machine",
    section: "special offers",
  },
  {
    id: 25,
    like: true,
    img: "WashingMachines.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "washing machine",
    amount: 2500500,
    ratings: 50,
    ratings_count: 10,
    slug: "Washing Machine",
    section: "special offers",
  },
  {
    id: 26,
    like: true,
    img: "WashingMachine2.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "washing machine",
    amount: 5999,
    ratings: 37,
    ratings_count: 9,
    slug: "Washing Machine",
    section: "latest deals",
  },
  {
    id: 27,
    like: true,
    img: "WashingMachine1.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "washing machine",
    amount: 90999,
    ratings: 60,
    ratings_count: 15,
    slug: "Washing Machine",
    section: "special offers",
  },
  {
    id: 28,
    like: true,
    img: "Blenders.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "blender",
    amount: 1500000,
    ratings: 45,
    ratings_count: 10,
    slug: "Blender",
    section: "latest deals",
  },
  {
    id: 29,
    like: true,
    img: "Blenders.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "blender",
    amount: 9999,
    ratings: 35,
    ratings_count: 7,
    slug: "Blender",
    section: "amazing discount",
  },
  {
    id: 30,
    like: true,
    img: "Blenders.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "blender",
    amount: 12999,
    ratings: 20,
    ratings_count: 5,
    slug: "Blender",
    section: "special offers",
  },
  {
    id: 31,
    like: false,
    img: "Blenders.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "blender",
    amount: 100500,
    ratings: 30,
    ratings_count: 8,
    slug: "Blender",
    section: "amazing discount",
  },
  {
    id: 32,
    like: true,
    img: "Blenders.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "blender",
    amount: 90999,
    ratings: 40,
    ratings_count: 10,
    slug: "Blender",
    section: "special offers",
  },
  {
    id: 33,
    like: false,
    img: "Blenders.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "blender",
    amount: 180999,
    ratings: 15,
    ratings_count: 4,
    slug: "Blender",
    section: "amazing discount",
  },
  {
    id: 34,
    like: true,
    img: "AirConditioners.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "air conditioner",
    amount: 75800,
    ratings: 40,
    ratings_count: 9,
    slug: "Air Conditioner",
    section: "special offers",
  },
  {
    id: 35,
    like: true,
    img: "AirConditioners.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "air conditioner",
    amount: 2500500,
    ratings: 50,
    ratings_count: 10,
    slug: "Air Conditioner",
    section: "latest deals",
  },
  {
    id: 36,
    like: true,
    img: "AirConditioners.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "air conditioner",
    amount: 5999,
    ratings: 37,
    ratings_count: 9,
    slug: "Air conditioner",
    section: "special offers",
  },
  {
    id: 37,
    like: true,
    img: "AirConditioners.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "air conditioner",
    amount: 90999,
    ratings: 60,
    ratings_count: 15,
    slug: "Air Conditioner",
    section: "special offers",
  },
  {
    id: 38,
    like: true,
    img: "Generator1.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "generator",
    amount: 1500000,
    ratings: 45,
    ratings_count: 10,
    slug: "Generator",
    section: "latest deals",
  },
  {
    id: 39,
    like: true,
    img: "Generator1.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "generator",
    amount: 9999,
    ratings: 35,
    ratings_count: 7,
    slug: "Generator",
    section: "amazing discount",
  },
  {
    id: 40,
    like: true,
    img: "Generator1.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "generator",
    amount: 12999,
    ratings: 20,
    ratings_count: 5,
    slug: "Generator",
    section: "amazing discount",
  },
  {
    id: 41,
    like: false,
    img: "Generator1.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "generator",
    amount: 100500,
    ratings: 30,
    ratings_count: 8,
    slug: "Generator",
    section: "amazing discount",
  },
  {
    id: 42,
    like: true,
    img: "Generator1.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "generator",
    amount: 90999,
    ratings: 40,
    ratings_count: 10,
    slug: "Generator",
    section: "amazing discount",
  },
  {
    id: 43,
    like: false,
    img: "Generator1.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "generator",
    amount: 180999,
    ratings: 15,
    ratings_count: 4,
    slug: "Generator",
    section: "special offers",
  },
  {
    id: 44,
    like: true,
    img: "Generator1.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "generator",
    amount: 75800,
    ratings: 40,
    ratings_count: 9,
    slug: "Generator",
    section: "latest deals",
  },
  {
    id: 45,
    like: true,
    img: "Generator1.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "generator",
    amount: 2500500,
    ratings: 50,
    ratings_count: 10,
    slug: "Generator",
    section: "special offers",
  },
  {
    id: 46,
    like: true,
    img: "Freezer1.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "freezer",
    amount: 5999,
    ratings: 37,
    ratings_count: 9,
    slug: "Freezer",
    section: "amazing discount",
  },
  {
    id: 47,
    like: true,
    img: "Fridge1.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "freezer",
    amount: 90999,
    ratings: 60,
    ratings_count: 15,
    slug: "Freezer",
    section: "special offers",
  },
  {
    id: 48,
    like: true,
    img: "Freezer1.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "freezer",
    amount: 1500000,
    ratings: 45,
    ratings_count: 10,
    slug: "Freezer",
    section: "amazing discount",
  },
  {
    id: 49,
    like: true,
    img: "Fridge1.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "freezer",
    amount: 9999,
    ratings: 35,
    ratings_count: 7,
    slug: "Freezer",
    section: "latest deals",
  },
  {
    id: 50,
    like: true,
    img: "Freezer1.svg",
    name: "GoPro HERO6 4K Action",
    description: "Camera - Black",
    category: "freezer",
    amount: 12999,
    ratings: 20,
    ratings_count: 5,
    slug: "Freezer",
    section: "special offers",
  },
];

export { Item };
export type { ItemType };
